# Generated by Django 5.1.6 on 2025-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_foto',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото рецепта'),
        ),
    ]
